### PR TITLE
[wip]Add yaml parsing support

### PR DESCRIPTION
**Pull request by pratikmallya**
depends on:  
- [ ] https://github.com/rackspace/rack/pull/320

### CODE REVIEW

**Comment by pratikmallya** [comment]
@jrperritt @rgbkrk So, I'm not sure how you guys want to go about adding new packages to rack. Let me know if there is a better way to add this package and I will work on it :)

**Comment by jrperritt** [comment]
Don't worry about that. I'll vendor the `orchestration` packages from Gophercloud and merge it to `master` tomorrow. Then you can merge `master` with your orchestration branch.

**Comment by jrperritt** [comment]
@pratikmallya Here's what I think we should do for now: instead of adding the Gophercloud repo to every orchestration PR, import the `rackspace/gophercloud` repo in your `orchestrationcommands` package. Namely, instead of using the Gophercloud files beneath the `internal` package, delete the Gophercloud orchestration files under that package from your branch and instead import, for example, `github.com/rackspace/gophercloud/openstack/orchestration/v1/stackevents`. Then, once the commands are merged and working, we can vendor the Gophercloud orchestration packages into `rack`. That will make it easier to review these PRs.

**Comment by pratikmallya** [comment]
@jrperritt sounds good. I'll also import the yaml package the same way. One thing to note is that I do need template parsing support for the orchestration commands to work correctly(https://github.com/rackspace/rack/pull/325), but i'll add that as a PR to gophercloud. Once that is reviewed and merge, I should be able to use gophercloud as you outlined above.

**Comment by pratikmallya** [comment]
closing in favor of https://github.com/rackspace/rack/pull/328

**Pull request closed without merging**
