### PR TITLE
Add submit issue link to Rackspace CLI reference

### PR DESCRIPTION
**Pull request by meker12**
Update _deconst.json to add meta data to support submit an issue link.  This feature lets people jump from the docs on DRC to the github repo to submit an issue.

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-9ab047e045/docs/rack-cli/). :bow:

**Comment by jrperritt** [comment]
SGTM. Is it ready to merge?

**Comment by meker12** [comment]
hmm... I don't see the submit issue link in the preview.  Oh... this is why.  @ktbartholomew  needs to update the "rack-cli.html" template to include the Github link styling.  Created an issue: https://github.com/rackerlabs/nexus-control/issues/431.

You can merge the change, or wait until issue #431 is resolved. I am pretty sure that adding the metadata now doesn't affect anything.  @ktbartholomew  Can you confirm?

**Comment by ktbartholomew** [comment]
@meker12 There should be no issue with merging this change before the templates have been updated to display the changes. 👍 :shipit:

**Comment by jrperritt** [comment]
+2

**Pull request merged**
