### PR TITLE
[wip]Add gophercloud support for cloud orchestration

### PR DESCRIPTION
**Pull request by pratikmallya**
Verbatim copy of orchestration resources from gophercloud.

### CODE REVIEW

**Comment by StephenBrown2** [comment]
Is this copying from gophercloud or importing the library and using its functionality?

Pardon my ignorance of golang development methodology.

**Comment by pratikmallya** [comment]
@StephenBrown2 this is copying verbatim from gophercloud. `rack` has a gophercloud under `internal/github.com/rackspace/gophercloud` so that is where the files are being copied to.

**Comment by StephenBrown2** [comment]
Hm. So I'm curious where the development is happening, will the orchestration be added upstream, or does it already exist upstream, and this is like, say, embedding Python 2.7 in a project to use that specific feature set?

Basically the question is: Why not just source the upstream and add features there, a la http://golang.org/cmd/go/#hdr-Remote_import_paths ?

**Comment by jnoller** [comment]
@stephenbrown2 the best practices for Go are "vendor and pin" your dependencies. That's why gophercloud is vendored wholesale; much like docker and it's dependencies. That said, we should probably freshen the pinned version as a whole and not just add in the orchestration chunk by hand.

**Comment by rgbkrk** [comment]
We use [govendor](https://github.com/kardianos/govendor) to vendorize dependencies. This should include updates to `internal/vendor.json`, facilitated through one of their subcommands (e.g. `govendor update github.com/rackspace/gophercloud`) or pinning the commit within `internal/vendor.json` and building it up again. That being said, I don't see changes to `internal/vendor.json`, which certainly need to happen (gophercloud has to come in wholesale, pinned to a version).

**Comment by rgbkrk** [comment]
Which does bring up a good point about our README and CONTRIBUTING guides not making *any* mention of *how* these are vendored (I had to go back and search issues to find the chosen tool).

While I was at it, posted #329 as a related issue.

**Comment by jrperritt** [comment]
https://github.com/rackspace/rack/pull/321#issuecomment-140157297

**Comment by pratikmallya** [comment]
closing in favor of https://github.com/rackspace/rack/pull/328

**Pull request closed without merging**
