### PR TITLE
1.0.0-beta.1 release notes

### PR DESCRIPTION
**Pull request by jrperritt**

### CODE REVIEW

**Comment by rgbkrk** [comment]
Went ahead and added these notes via https://github.com/rackspace/rack/tags to https://github.com/rackspace/rack/releases/tag/1.0.0-beta.1

**Comment by jrperritt** [comment]
ah, that's great!

**Comment by rgbkrk** [comment]
Yeah, love gh releases. :wink:

**Comment by carolynvs** [comment]
:+1:

**Pull request merged**
