### PR TITLE
update latest version on release; closes #316

### LINKED ISSUE #316: endpoint in `docs` to get latest version
In order to let users know if they have the latest version or not, we need a reliable way to query the latest version. We could use the Github API, but there would be rate limits for users, and it returns a bunch of information we don't need. I think the easiest way might be to have an unlinked file under the `docs` that gets updated when the `release` script is run (something like `/docs/latest.json`). The JSON object would be short: `{version: "1.0.0-beta.1"}`, but may also contain the commit hash and/or the CDN container so that we can build the URLs and point users to where they can download the latest version.

Maybe there's a better way to do this?

### PR DESCRIPTION
**Pull request by jrperritt**

### CODE REVIEW

**Comment by jrperritt** [comment]
Hmm, I'm not sure `preparer-sphinx` will pick up `.json` files. 
@smashwilson @ktbartholomew Is there a way to have a one-off route in `deconst`? Specifically, I'd like `docs/latest.json` to map to `https://developer.rackspace.com/docs/rack-cli/latest.json`. It would be unlinked (inaccessible from the site) and would just return a JSON document when queried.

**Comment by smashwilson** [comment]
@jrperritt Yeah, I think so. Two options:

1. We could add a [proxy route](https://github.com/rackerlabs/nexus-control/blob/master/config/content.json#L9-L11) to map any requests that have a specific prefix to an arbitrary other service, like, say, `raw.github.com`. Then you could maintain the JSON document somewhere in the GitHub repository.

2. We can add the route to deconst as normal content, specify a "null template" for that path like [the one we use for the RSS feed](https://github.com/rackerlabs/nexus-control/blob/master/templates/developer.rackspace.com/feed.xml), and submit the raw metadata envelope with a `curl`, maybe from Travis' deploy step.

Option 2 is a little cleaner maybe, but I think option 1 would be easier. Which would you prefer?

**Comment by jrperritt** [comment]
Great :)

I'd say whichever's easiest, so Option 1 would be fine.

**Comment by rgbkrk** [comment]
This PR is way out of date, I'm going to go ahead and close it.

**Comment by StephenBrown2** [comment]
Is there any initiative to check for the latest version and prompt the user? Or even a way to check it manually?

Running `curl -s https://raw.githubusercontent.com/rackspace/rack/master/docs/index.rst | awk '/_Linux/{split($NF,s,"/"); print s[4],$NF}'` to check the latest version and download it seems suboptimal to me.

**Comment by rgbkrk** [comment]
It would be nice if we had a JSON file we generate that lists the current versions, similar to the other gunk we generate for docs builds. That or a plain file.

**Comment by StephenBrown2** [comment]
...Isn't that exactly what this PR was to implement?

Granted, it only listed the latest version, but do we need the JSON file to list ALL the versions?

**Pull request closed without merging**
