### PR TITLE
Use the = sign form for LDFLAGS conditionally

### PR DESCRIPTION
**Pull request by rgbkrk**
Suppress warnings with low ball tricks.

In support of #339.

### CODE REVIEW

**Comment by jrperritt** [comment]
:+1:

**Comment by lvh** [comment]
LGTM :)

**Comment by rgbkrk** [comment]
Want to make a patch release @jrperritt, so that the brew recipe can get going sooner?

**Comment by jrperritt** [comment]
Yeah, I'll do that now.

**Comment by jrperritt** [comment]
To follow up, before pushing a 1.0.1 release, we're going to amend the `release` script to work on both Mac and Linux.

**Comment by jrperritt** [comment]
@lvm Pushed a 1.0.1 release that shouldn't give warnings.

**Pull request merged**
