### PR TITLE
[wip] Add support for cloud orchestration

### PR DESCRIPTION
**Pull request by pratikmallya**
Adds support for cloud orchestration commands.

### CODE REVIEW

**Comment by jrperritt** [comment]
https://github.com/rackspace/rack/pull/321#issuecomment-140157297

**Comment by pratikmallya** [comment]
@jrperritt I'm keeping only this PR open to track the changes to add orchestration commands. I'll rebase them onto master once you've vendored in orchestration with the changes I've proposed

**Comment by pratikmallya** [comment]
@jrperritt once https://github.com/rackspace/gophercloud/pull/486 is merged and vendored into rack, I will rebase this branch and submit it for review. Note that the commands part are ready for review.

**Comment by jrperritt** [comment]
At least one orchestration import for each Gophercloud orchestration file to be vendored (like [here](https://github.com/pratikmallya/rack/blob/add_orchestration_documentation/commands/orchestrationcommands/buildinfocommands/buildinfo.go#L8)) need to use `github.com/rackpsace/gophercloud`. Otherwise the vendoring tool won't vendor it.

**Comment by pratikmallya** [comment]
closing in favour of https://github.com/rackspace/rack/pull/346.

**Pull request closed without merging**
