### PR TITLE
[rfr] Vendor Gophercloud files for CDBs

### PR DESCRIPTION
**Pull request by jamiehannaford**

### CODE REVIEW

**Comment by carolynvs** [comment]
I just did some minor testing: list flavors, instances and created an instance. :+1:

**Comment by jamiehannaford** [comment]
@jrperritt would you mind having a look whenever you get some free time?

**Comment by jrperritt** [comment]
@jamiehannaford Github is having a hard time handling all the files in this PR. Let's split it into 2: the first can just vendor the Gophercloud DB files, and then, after that one is merged, the second can be rebased on top of that.

**Comment by jamiehannaford** [comment]
@jrperritt Stripped out a bunch of files. This is just the `internal` stuff now.

**Comment by jrperritt** [comment]
+2

**Pull request merged**
